version: '3'
services:
  nodejs:
    image: node:lts-alpine
    user: node
    volumes:
      - .:/app
      - ./openlayers:/app/openlayers
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache git
        git config --global --add safe.directory /app
        git config --global --add safe.directory /openlayers
        yarn
        yarn prepare-npm $ARGS
