name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Cloning openlayers repository
        run: git clone https://github.com/openlayers/openlayers
      - run: yarn --frozen-lockfile
      - run: yarn prepare-npm
